import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
VERSION_FILE = ROOT / "_version.py"
OUT_FILE = ROOT / "file_version_info.txt"


def parse_version():
    text = VERSION_FILE.read_text(encoding="utf-8")
    match = re.search(r"__version__\s*=\s*['\"]([^'\"]+)['\"]", text)
    if not match:
        raise ValueError("Could not parse __version__ from _version.py")

    raw = match.group(1).strip().lstrip("v")
    parts = []
    for chunk in raw.split("."):
        digits = "".join(ch for ch in chunk if ch.isdigit())
        parts.append(int(digits) if digits else 0)
    while len(parts) < 4:
        parts.append(0)

    display = ".".join(str(p) for p in parts[:4])
    return display, tuple(parts[:4])


def render(version_text, version_tuple):
    major, minor, patch, build = version_tuple
    return f'''# UTF-8
# Auto-generated by generate_version_info.py. Do not edit manually.

VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({major}, {minor}, {patch}, {build}),
    prodvers=({major}, {minor}, {patch}, {build}),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [
          StringStruct('CompanyName', 'Silviu Dobrica'),
          StringStruct('FileDescription', 'Bing Daily Wallpaper Tray App'),
          StringStruct('FileVersion', '{version_text}'),
          StringStruct('InternalName', 'BingWallpaper'),
          StringStruct('LegalCopyright', 'Copyright (C) 2026 Silviu Dobrica'),
          StringStruct('OriginalFilename', 'BingWallpaper.exe'),
          StringStruct('ProductName', 'Bing Daily Wallpaper'),
          StringStruct('ProductVersion', '{version_text}')
        ]
      )
    ]),
    VarFileInfo([
      VarStruct('Translation', [1033, 1200])
    ])
  ]
)
'''


def main():
    version_text, version_tuple = parse_version()
    content = render(version_text, version_tuple)
    OUT_FILE.write_text(content, encoding="utf-8")
    print(f"Generated {OUT_FILE.name} for version {version_text}")


if __name__ == "__main__":
    main()
